# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-08 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='otp_created_time',
            field=models.CharField(blank=True, default=b'', max_length=100),
        ),
    ]
